--- 
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
etcd:
  local:
    dataDir: /var/lib/etcd
    extraArgs:
      heartbeat-interval: 250
      election-timeout: 2500
      snapshot-count: 6400
      auto-compaction-mode: periodic
      auto-compaction-retention: 8h
