---
#- job:
#    name: test_conformance
#    parent: openstack-access-base
#    description: |
#      Run tests of the configuration on test Kubernetes cluster using
#      [sonobuoy](https://sonobuoy.io/) with mode conformance meaning
#      it will test if the Kubernetes cluster is conformant to the CNCF.
#    run: playbooks/test.yaml
#    cleanup-run: playbooks/cleanup.yaml
#    vars:
#      test: conformance
#
#- job:
#    name: test_quick
#    parent: openstack-access-base
#    description: |
#      Run tests of the configuration on test Kubernetes cluster using
#      [sonobuoy](https://sonobuoy.io/) with mode quick.
#    run: playbooks/test.yaml
#    cleanup-run: playbooks/cleanup.yaml
#    vars:
#      test: quick

- job:
    name: e2e_test
    parent: openstack-access-base
    run: playbooks/test.yaml
    cleanup-run: playbooks/cleanup.yaml # executed also when the job is canceled
    vars:
      project_tf_dir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/terraform"
      cloud_provider: "{{ cloud }}" # inherited from the parent job

- project:
    e2e-conformance:
      jobs:
      - e2e_test:
          description: |
            Run tests of the configuration on test Kubernetes cluster using 
            [sonobuoy](https://sonobuoy.io/) with mode conformance meaning 
            it will test if the Kubernetes cluster is conformant to the CNCF.
          vars:
            test: conformance
          timeout: 7200
    e2e-quick:
      jobs:
      - e2e_test:
          description: |
            Run tests of the configuration on test Kubernetes cluster using 
            [sonobuoy](https://sonobuoy.io/) with mode quick.
          vars:
            test: quick
