---
- job:
    name: test_conformance
    parent: openstack-access-base
    description: |
      Run tests of the configuration on test Kubernetes cluster using
      [sonobuoy](https://sonobuoy.io/) with mode conformance meaning
      it will test if the Kubernetes cluster is conformant to the CNCF.
    run: playbooks/test.yaml
    cleanup-run: playbooks/cleanup.yaml # executed also when the job is canceled
    vars:
      test: conformance
      wait_for_cluster: 2 # minutes
    timeout: 10800

- job:
    name: test_quick
    parent: openstack-access-base
    description: |
      Run tests of the configuration on test Kubernetes cluster using
      [sonobuoy](https://sonobuoy.io/) with mode quick.
    run: playbooks/test.yaml
    cleanup-run: playbooks/cleanup.yaml # executed also when the job is canceled
    vars:
      test: quick
      wait_for_cluster: 1 # minutes
    timeout: 2700

#- job:
#    name: e2e_test
#    parent: openstack-access-base
#    run: playbooks/test.yaml
#    cleanup-run: playbooks/cleanup.yaml # executed also when the job is canceled
#    vars:
#      cloud_provider: "{{ cloud }}" # inherited from the parent job
#      project_tf_dir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/terraform"
#      wait_for_cluster: 1 # minutes

- project:
    e2e-test:
      jobs:
      - test_conformance
    e2e-quick-test:
      jobs:
      - test_quick
