---
- job:
    name: mqtt-matrix-bridge-test
    parent: base
    run: playbooks/test.yaml

- project:
    name: matofederorg/k8s-cluster-api-provider
    default-branch: main
    merge-mode: "squash-merge"
    periodic-hourly:
      jobs:
      - mqtt-matrix-bridge-test