---
- job:
    name: test_conformance
    parent: openstack-access-base
    description: |
      Run tests of the configuration on test Kubernetes cluster using 
      [sonobuoy](https://sonobuoy.io/) with mode conformance meaning 
      it will test if the Kubernetes cluster is conformant to the CNCF.
    run: playbooks/test_conformance.yaml

- job:
    name: test_quick
    parent: openstack-access-base
    description: |
      Run tests of the configuration on test Kubernetes cluster using 
      [sonobuoy](https://sonobuoy.io/) with mode quick.
    run: playbooks/test_quick.yaml

- project:
    e2e-conformance:
      jobs:
        - test_conformance
    e2e-quick:
      jobs:
        - test_quick
