---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  annotations:
    loadbalancer.openstack.org/enable-health-monitor: "false"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
