---
- name: Install jq
  get_url:
    url: "https://github.com/jqlang/jq/releases/download/jq-{{ jq_version }}/jq-linux64"
    dest: "/usr/bin/jq"
    mode: "+x"
    # TODO: use `checksum` attr here to verify the digest of the destination file, if available
- name: Install yq
  get_url:
    url: "https://github.com/mikefarah/yq/releases/download/v{{ yq_version }}/yq_linux_arm64"
    dest: "/usr/bin/yq"
    mode: "+x"
    # TODO: use `checksum` attr here to verify the digest of the destination file, if available
- name: Install openstack client dependencies
  pip:
    name:
    - "python-openstackclient=={{ openstackclient_version }}"
    - "python-octaviaclient=={{ octaviaclient_version }}"
