apiVersion: infrastructure.cluster.x-k8s.io/v1alpha7
kind: OpenStackClusterTemplate
metadata:
  name: {{ .Values.testcluster_name }}
  namespace: {{ .Values.testcluster_name }}
spec:
  template:
    spec:
      cloudName: {{ .Values.prefix }}-{{ .Values.testcluster_name }}
      identityRef:
        name: {{ .Values.testcluster_name }}-cloud-config
        kind: Secret
      apiServerLoadBalancer:
        enabled: true
      managedSecurityGroups: true
      nodeCidr: {{ .Values.node_cidr }}
      dnsNameservers: {{ .Values.dns_nameservers }}
      externalNetworkId: {{ .Values.external_id }}
