---
- name: Cleanup
  hosts: all
  vars:
    cloud_provider: "{{ cloud }}" # inherited from the parent job
    project_tf_dir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/terraform"
  environment:
    ENVIRONMENT: "{{ cloud_provider }}"
  tasks:
  - name: Cleanup
    import_tasks: fullclean.yaml
