---
- name: Cleanup
  hosts: all
  vars:
    cloud_provider: "{{ cloud }}"  # inherited from the parent job
    project_dir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
    project_tf_dir: "{{ project_dir }}/terraform"
    # Some Kubernetes resources managed by the k8s-cluster-api-provider project employ names
    # formed by combining elements such as a prefix, cluster-name, and additional suffix.
    # This combined naming convention may potentially exceed the character limits imposed by
    # Kubernetes. To mitigate this issue, we take precautions by truncating both the prefix
    # and the cluster name to 12 characters each. This adjustment ensures that we stay
    # within Kubernetes' limits and allows us to utilize a single OpenStack project with
    # multiple k8s-capi deployments.
    pr_or_main: "{{ 'pr' + zuul.change if zuul.change is defined else 'main' }}"
    prefix: "{{ (pr_or_main + '-' + zuul.build) | truncate(12, True, '') }}"
    testcluster_name: "{{ (pr_or_main + '-' + zuul.build) | truncate(12, True, '') }}"
  environment:
    ENVIRONMENT: "{{ cloud_provider }}"
    PATH: "{{ ansible_user_dir }}/.local/bin:{{ ansible_env.PATH }}"
  tasks:
  - name: Ensure environment file
    template:
      src: "templates/environment.tfvars.j2"
      dest: "{{ project_tf_dir }}/environments/environment-{{ cloud_provider }}.tfvars"
  - name: Cleanup - forceclean
    command: "make forceclean"
    args:
      chdir: "{{ project_tf_dir }}"
