---
- name: Get PR details
  uri:
    url: "https://api.github.com/repos/{{ zuul.project.name }}/pulls/{{ zuul.change }}"
    body_format: json
    headers:
      Accept: application/vnd.github+json
      X-GitHub-Api-Version: 2022-11-28
  register: pull_request

- name: Create k8s cluster
  command: "make create GITBRANCH={{ pull_request.json.head.ref }} GITREPO={{ pull_request.json.head.repo.clone_url }}"
  args:
    chdir: "{{ project_tf_dir }}"
