---
- name: Ensure k8s-cluster-api-provider project dependencies
  hosts: all
  vars:
    jq_version: "1.6"
    yq_version: "4.35.1"
    kubectl_version: "1.28.1"
    openstackclient_version: "6.2.0"
    octaviaclient_version: "3.4.0"
    opentofu_version: "1.6.0-beta1"
    install_dir: "{{ ansible_user_dir }}/.local/bin"
  environment:
    PATH: "{{ install_dir }}:{{ ansible_env.PATH }}"
  roles:
  - role: ensure-pip  # https://zuul-ci.org/docs/zuul-jobs/latest/python-roles.html#role-ensure-pip
  tasks:
  - name: Make sure installation directory exists
    ansible.builtin.file:
      path: "{{ install_dir }}"
      state: directory
      mode: 0755
  - name: Install jq
    ansible.builtin.get_url:
      url: "https://github.com/jqlang/jq/releases/download/jq-{{ jq_version }}/jq-linux64"
      dest: "{{ install_dir }}/jq"
      mode: "+x"
      # TODO: use `checksum` attr here to verify the digest of the destination file, if available
  - name: Install yq
    ansible.builtin.get_url:
      url: "https://github.com/mikefarah/yq/releases/download/v{{ yq_version }}/yq_linux_amd64"
      dest: "{{ install_dir }}/yq"
      mode: "+x"
      # TODO: use `checksum` attr here to verify the digest of the destination file, if available
  - name: Install kubectl
    ansible.builtin.get_url:
      url: "https://dl.k8s.io/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl"
      dest: "{{ install_dir }}/kubectl"
      mode: "+x"
      # TODO: use `checksum` attr here to verify the digest of the destination file, if available
  - name: Install openstack client dependencies
    ansible.builtin.pip:
      name:
      - "python-openstackclient=={{ openstackclient_version }}"
      - "python-octaviaclient=={{ octaviaclient_version }}"
      extra_args: --user
  - name: Install ip command
    ansible.builtin.package:
      name: iproute2
    become: true
  - name: Install OpenTofu
    # TODO: write separate role ensure-opentofu, see https://opendev.org/zuul/zuul-jobs/src/branch/master/roles/ensure-terraform
    block:
      - name: Install unzip
        ansible.builtin.package:
          name: unzip
        become: true
      - name: Create temp directory
        ansible.builtin.tempfile:
          state: directory
        register: tofu_install_tempdir
      - name: Download OpenTofu archive
        ansible.builtin.get_url:
          url: "https://github.com/opentofu/opentofu/releases/download/v{{ opentofu_version }}/tofu_{{ opentofu_version }}_linux_amd64.zip"
          dest: "{{ tofu_install_tempdir.path }}/opentofu.zip"
          mode: 0644
      # TODO: checksum
      - name: Create OpenTofu package directory
        ansible.builtin.file:
          path: "{{ tofu_install_tempdir.path }}/opentofu"
          state: directory
          mode: 0755
      - name: Unarchive OpenTofu
        ansible.builtin.unarchive:
          src: "{{ tofu_install_tempdir.path }}/opentofu.zip"
          dest: "{{ tofu_install_tempdir.path }}/opentofu"
          remote_src: true
      - name: Install OpenTofu
        ansible.builtin.copy:
          src: "{{ tofu_install_tempdir.path }}/opentofu/tofu"
          dest: "{{ install_dir }}/tofu"
          mode: "+x"
          remote_src: true
      - name: Remove temp directory
        ansible.builtin.file:
          path: "{{ tofu_install_tempdir }}"
          state: absent
      - name: Output OpenTofu version
        ansible.builtin.command: "tofu version"
        register: tofu_version
        changed_when: tofu_version.rc != 0
