---
- name: E2E test
  hosts: all
  vars:
    cloud_provider: "{{ cloud }}"  # inherited from the parent job
    project_dir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
    project_tf_dir: "{{ project_dir }}/terraform"
    git_reference_default: "main"  # A fallback used when the git_reference variable is undefined and the pipeline is not executed on a PR
    git_repo_default: "https://github.com/SovereignCloudStack/k8s-cluster-api-provider.git"  # A fallback used when the git_repo variable is undefined and the pipeline is not executed on a PR
    # Some Kubernetes resources managed by the k8s-cluster-api-provider project employ names
    # formed by combining elements such as a prefix, cluster-name, and additional suffix.
    # This combined naming convention may potentially exceed the character limits imposed by
    # Kubernetes. To mitigate this issue, we take precautions by truncating both the prefix
    # and the cluster name to 12 characters each. This adjustment ensures that we stay
    # within Kubernetes' limits and allows us to utilize a single OpenStack project with
    # multiple k8s-capi deployments.
    pr_or_main: "{{ 'pr' + zuul.change if zuul.change is defined else 'main' }}"
    prefix: "{{ (pr_or_main + '-' + zuul.build) | truncate(12, True, '') }}"
    testcluster_name: "{{ (pr_or_main + '-' + zuul.build) | truncate(12, True, '') }}"
  environment:
    ENVIRONMENT: "{{ cloud_provider }}"
    PATH: "{{ ansible_user_dir }}/.local/bin:{{ ansible_env.PATH }}"
  tasks:
  - name: Prepare environment
    block:
    - name: Get PR details
      ansible.builtin.uri:
        url: "https://api.github.com/repos/{{ zuul.project.name }}/pulls/{{ zuul.change }}"
        body_format: json
        headers:
          Accept: application/vnd.github+json
          X-GitHub-Api-Version: 2022-11-28
      register: pull_request
      when: zuul.change is defined  # execute when the e2e pipeline is initiated on a PR
    - name: |
        Set facts -
        Priority is given to the values of git_reference and git_repo over variables collected from the PR.
        In cases where git_reference and git_repo are undefined, and e2e is not executed on the PR, a fallback mechanism is employed.
      ansible.builtin.set_fact:
        git_branch_name: "{{ git_reference | default(pull_request.json.head.ref) | default(git_reference_default) }}"
        git_repository_url: "{{ git_repo | default(pull_request.json.head.repo.clone_url) | default(git_repo_default) }}"
    - name: Checkout to PR branch
      ansible.builtin.git:
        repo: "{{ git_repository_url }}"
        clone: false
        dest: "{{ project_dir }}"
        version: "{{ git_branch_name }}"
      when: zuul.change is defined  # execute when the e2e pipeline is initiated on a PR
    - name: Extract Zuul config
      ansible.builtin.set_fact:
        zuul_config: "{{ zuul.change_message | regex_search('(?s)```ZUUL_CONFIG(.+?)```', '\\1', multiline=true) }}"
      when: zuul.change_message is defined
    - name: Trim Zuul config
      ansible.builtin.set_fact:
        zuul_config: "{{ zuul_config  | first | split('/n') | map('trim') | join('\n') }}"
      when: zuul_config is defined and zuul_config is not none and zuul_config != ''
    - name: Print Zuul config
      ansible.builtin.debug:
        var: zuul_config
    - name: Create environment file
      ansible.builtin.template:
        src: "templates/environment.tfvars.j2"
        dest: "{{ project_tf_dir }}/environments/environment-{{ cloud_provider }}.tfvars"
        mode: "0644"
    - name: Get default interface name
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          ip route show default | head -n1 | sed 's/^.*dev \([^ ]*\).*$/\1/'
        executable: /bin/bash
      register: dev
      changed_when: false
    - name: Get default interface MTU
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          ip link show {{ dev.stdout }} | head -n1 | sed 's/^.*mtu \([^ ]*\).*$/\1/'
        executable: /bin/bash
      register: mtu
      changed_when: false
    - name: Set mtu for the default interface  # workaround for terraform file provisioner scp error
      ansible.builtin.command: "ip link set {{ dev.stdout }} mtu 1500"
      become: true
      when: mtu.stdout != "1500"
      changed_when: mtu.stdout != "1500"
  - name: Create k8s cluster and execute sonobouy check
    block:
    - name: Create k8s cluster
      ansible.builtin.command: "make create GITREFERENCE={{ git_branch_name }} GITREPO={{ git_repository_url }}"
      args:
        chdir: "{{ project_tf_dir }}"
      changed_when: true
    - name: Get kubeconfig of the workload k8s cluster
      ansible.builtin.command: "make get-kubeconfig TESTCLUSTER={{ testcluster_name }}"
      args:
        chdir: "{{ project_tf_dir }}"
      changed_when: true
    - name: Wait for all system pods in the workload k8s cluster to become ready
      ansible.builtin.command: "kubectl wait -n kube-system --for=condition=Ready --timeout={{ wait_for_cluster }}s pod --all"
      args:
        chdir: "{{ project_tf_dir }}"
      environment:
        KUBECONFIG: "{{ testcluster_name }}.yaml.{{ cloud_provider }}"
      changed_when: true
    - name: Execute sonobouy check mode {{ sonobouy_mode }}
      ansible.builtin.command: "make check-{{ sonobouy_mode }}"
      register: sonobouy_results
      args:
        chdir: "{{ project_tf_dir }}"
      changed_when: true
    always:
    - name: Parse sonobouy results  # noqa: ignore-errors
      ansible.builtin.set_fact:
        sonobouy_results_parsed: "{{ sonobouy_results.stdout | regex_search('=== Collecting results ===[\\S\\s]*') }}"
      when: sonobouy_results is defined
      ignore_errors: true  # ignore when this task failed as it is nice to have, and we should ensure that fullclean is reached
    - name: Insert parsed sonobouy results to the warning message that will be appended to the comment zuul leaves on the PR  # noqa: ignore-errors
      zuul_return:
        data:
          zuul:
            warnings:
              - "<details>\n  <summary><b>Sonobouy results</b></summary>\n{{ sonobouy_results_parsed }}\n</details>"
      when: sonobouy_results_parsed is defined and sonobouy_results_parsed | length > 0
      ignore_errors: true  # ignore when this task failed as it is nice to have, and we should ensure that fullclean is reached
    - name: Cleanup - fullclean
      ansible.builtin.command: "make fullclean"
      args:
        chdir: "{{ project_tf_dir }}"
      changed_when: true
