---
- name: E2E test
  hosts: all
  roles:
  - ensure-dependencies
  vars:
    mode: "{{ test }}"
  environment:
    ENVIRONMENT: "{{ cloud_provider }}"
  tasks:
  - name: Create k8s cluster and run check-{{ mode }}
    block:
    - name: Create environment file
      import_tasks: create_env_file.yaml
    - name: Create k8s cluster
      import_tasks: create.yaml
    - name: Execute sonobouy {{ mode }} check
      import_tasks: check.yaml
    always:
    - name: Cleanup
      import_tasks: fullclean.yaml
