---
apiVersion: v1
data:
  config.yaml: |
    trivy:
      enabled: true
      replicas: 2
    portal:
      replicas: 2
    core:
      replicas: 2
    jobservice:
      replicas: 2
      jobLoggers:
      - database
    registry:
      replicas: 2
    metrics:
      enabled: true
    cache:
      enabled: true
    expose:
      type: ingress
      tls:
        enabled: true
        certSource: secret
        secret:
          secretName: harbor-crt
      ingress:
        hosts:
          core: ${HARBOR_DOMAIN_NAME}
        className: nginx
        harbor:
          annotations:
            cert-manager.io/issuer: letsencrypt
            nginx.ingress.kubernetes.io/limit-rps: "25"
    externalURL: https://${HARBOR_DOMAIN_NAME}
    database:
      type: internal
    redis:
      type: internal
    persistence:
      enabled: ${HARBOR_PERSISTENCE}
      persistentVolumeClaim:
        database:
          size: ${HARBOR_DATABASE_SIZE}
        redis:
          size: ${HARBOR_REDIS_SIZE}
        trivy:
          size: ${HARBOR_TRIVY_SIZE}
      imageChartStorage:
        type: s3
        s3:
          # generated by s3-credentials.bash
          existingSecret: s3-credentials
          regionendpoint: ${HARBOR_S3_ENDPOINT}
          bucket: ${HARBOR_S3_BUCKET}
          region: ${HARBOR_S3_REGION}
kind: ConfigMap
metadata:
  name: harbor-config
