---
name: Check opentofu syntax

"on":
  push:
    paths:
      - 'terraform/**'
      - '.github/workflows/check-opentofu-syntax.yml'
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/check-opentofu-syntax.yml'

jobs:
  check-opentofu-syntax:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: create config
        run: cp clouds.yaml.sample clouds.yaml
        working-directory: ./terraform
      - name: create credentials
        run: cp secure.yaml.sample secure.yaml
        working-directory: ./terraform
      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.6.0  # renovate: datasource=github-releases depName=opentofu/opentofu
      - name: Tofu init
        run: tofu init
        working-directory: ./terraform
      - name: Tofu validate
        run: tofu validate
        working-directory: ./terraform
        env:
          ENVIRONMENT: gx-betacloud
      - name: Tofu format
        run: tofu fmt -check
        working-directory: ./terraform
