---
name: Check terraform syntax

"on":
  push:
    paths:
      - 'terraform/**'
      - '.github/workflows/check-terraform-syntax.yml'
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/check-terraform.yml'

jobs:
  check-terraform-syntax:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: create config
        run: cp clouds.yaml.sample clouds.yaml
        working-directory: ./terraform
      - name: create credentials
        run: cp secure.yaml.sample secure.yaml
        working-directory: ./terraform
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6  # renovate: datasource=github-releases depName=hashicorp/terraform
      - name: Terraform init
        run: terraform init
        working-directory: ./terraform
      - name: Terraform validate
        run: terraform validate
        working-directory: ./terraform
        env:
          ENVIRONMENT: gx-betacloud
      - name: Terraform format
        run: terraform fmt -check
        working-directory: ./terraform
