---
name: Mark and close stale issues

"on":
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        exempt-all-issue-assignees: true  #  the issues with an assignee will not be marked as stale automatically
        stale-issue-message: "This issue is stale because it has been open 30 days with no activity. Remove stale label or comment, or this will be closed in 60 days."
        close-issue-message: "This issue was closed because it has been stalled for 60 days with no activity."
        stale-issue-label: "stale"
        exempt-issue-labels: "longterm,epic"
        days-before-issue-stale: 30
        days-before-issue-close: 60
        days-before-pr-stale: -1  # disabled for PRs
        days-before-pr-close: -1  # disabled for PRs
